services:
  db:
    image: postgres
    container_name: gerenciador-estoque-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: gerenciador-estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: "gerenciador-estoque-api"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gerenciador-estoque-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: gerenciador-estoque-db
      DB_PORT: 5432
      DB_NAME: gerenciador-estoque
      TZ: "America/Sao_Paulo"

volumes:
  postgres_data: